<?php

namespace App\Web\Presenters;

use Nette\Application\UI\Presenter;

class BasePresenter extends Presenter
{
    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }
}